// Generated by gencpp from file rosjava_test_msgs/TestString.msg
// DO NOT EDIT!


#ifndef ROSJAVA_TEST_MSGS_MESSAGE_TESTSTRING_H
#define ROSJAVA_TEST_MSGS_MESSAGE_TESTSTRING_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rosjava_test_msgs
{
template <class ContainerAllocator>
struct TestString_
{
  typedef TestString_<ContainerAllocator> Type;

  TestString_()
    : caller_id()
    , orig_caller_id()
    , data()  {
    }
  TestString_(const ContainerAllocator& _alloc)
    : caller_id(_alloc)
    , orig_caller_id(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _caller_id_type;
  _caller_id_type caller_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _orig_caller_id_type;
  _orig_caller_id_type orig_caller_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::rosjava_test_msgs::TestString_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosjava_test_msgs::TestString_<ContainerAllocator> const> ConstPtr;

}; // struct TestString_

typedef ::rosjava_test_msgs::TestString_<std::allocator<void> > TestString;

typedef boost::shared_ptr< ::rosjava_test_msgs::TestString > TestStringPtr;
typedef boost::shared_ptr< ::rosjava_test_msgs::TestString const> TestStringConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosjava_test_msgs::TestString_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosjava_test_msgs::TestString_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rosjava_test_msgs::TestString_<ContainerAllocator1> & lhs, const ::rosjava_test_msgs::TestString_<ContainerAllocator2> & rhs)
{
  return lhs.caller_id == rhs.caller_id &&
    lhs.orig_caller_id == rhs.orig_caller_id &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rosjava_test_msgs::TestString_<ContainerAllocator1> & lhs, const ::rosjava_test_msgs::TestString_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rosjava_test_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rosjava_test_msgs::TestString_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosjava_test_msgs::TestString_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosjava_test_msgs::TestString_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosjava_test_msgs::TestString_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosjava_test_msgs::TestString_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosjava_test_msgs::TestString_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosjava_test_msgs::TestString_<ContainerAllocator> >
{
  static const char* value()
  {
    return "334ff4377be93faa44ebc66d23d40fd3";
  }

  static const char* value(const ::rosjava_test_msgs::TestString_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x334ff4377be93faaULL;
  static const uint64_t static_value2 = 0x44ebc66d23d40fd3ULL;
};

template<class ContainerAllocator>
struct DataType< ::rosjava_test_msgs::TestString_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosjava_test_msgs/TestString";
  }

  static const char* value(const ::rosjava_test_msgs::TestString_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosjava_test_msgs::TestString_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Integration test message\n"
"# caller_id of most recent node to send this message\n"
"string caller_id\n"
"# caller_id of the original node to send this message\n"
"string orig_caller_id\n"
"string data\n"
;
  }

  static const char* value(const ::rosjava_test_msgs::TestString_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosjava_test_msgs::TestString_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.caller_id);
      stream.next(m.orig_caller_id);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TestString_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosjava_test_msgs::TestString_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosjava_test_msgs::TestString_<ContainerAllocator>& v)
  {
    s << indent << "caller_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.caller_id);
    s << indent << "orig_caller_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.orig_caller_id);
    s << indent << "data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSJAVA_TEST_MSGS_MESSAGE_TESTSTRING_H
