set(_CATKIN_CURRENT_PACKAGE "my_python_package")
set(my_python_package_VERSION "0.0.0")
set(my_python_package_MAINTAINER "ashley_garcia <ashley_garcia@todo.todo>")
set(my_python_package_PACKAGE_FORMAT "2")
set(my_python_package_BUILD_DEPENDS "rospy" "std_msgs")
set(my_python_package_BUILD_EXPORT_DEPENDS "rospy" "std_msgs")
set(my_python_package_BUILDTOOL_DEPENDS "catkin")
set(my_python_package_BUILDTOOL_EXPORT_DEPENDS )
set(my_python_package_EXEC_DEPENDS "rospy" "std_msgs")
set(my_python_package_RUN_DEPENDS "rospy" "std_msgs")
set(my_python_package_TEST_DEPENDS )
set(my_python_package_DOC_DEPENDS )
set(my_python_package_URL_WEBSITE "")
set(my_python_package_URL_BUGTRACKER "")
set(my_python_package_URL_REPOSITORY "")
set(my_python_package_DEPRECATED "")